travis:
  secure:
    BINSTAR_TOKEN: UzE6HKOhnpVoCVHEgrDvw9l6524rYYEX3/0AQn6QtWidUktydeHjvTRnB9/7Q2OO6kI3fpnKOjI37d5LI4sSVKkcvY2gA+VvwoW43GF1F/IazSILSfODd0zT9j+Voh/eFP+Sen4Wgd3f4N2qQKO38oYZO7LGKoW3UlwV6mS/XyZkMKI6mNMHGvwcjzN0w4xM8ZO/3KxgzmiDmdIt3ShZsk9d8auYLz17Y3Ebf6WR1raj8vnbx5MIQb6VYiaLIk31XPHOFVnwZsAGu1Ka3s2fb3ePOwzF5rrDrlTiOg/JFoo/FqNLqA+dpvXt0+5FLu29nG4QjJYYpU3Mp2Ju0FgQ05GVGJAz/CW/2BkDonglFVVnz8xxSaNuG6yZJlF3ER2KLQ21+wlQic5g/naN9mJ/2kfF1GS63Gro01SK+Ixofja6Hlx2etgExVHTSV+qFib1TcbvfdDbNdcZ/tvUOx6cjCyPx+m+cT1H8XGzw5sWaClRWS5d9RgjT23mdD1ssxaE4x5PBlQVmskoaLujcKd5EUm5qyDV6VYf5QWWVabBjJ/ZGueRtPhYNTNi3ZfuIoBfx1Lk4XGjmRVygIMneRKx0M7EgFFKUtljCfDTKepxUlOojdA5MWOA05Els+R/mk0RkEOgTuowwSlq6fGCOb5KMWXakrLvpXEMvBC7dsxOikc=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
